### PR TITLE
Adding TrueVaultUserStore

### PR DESCRIPTION
**Pull request by zopf**
adding access to the Users API https://docs.truevault.com/Users.html

### CODE REVIEW

**Comment by DaniilHarik** [comment]
Any chance this getting merged?

**Comment by zopf** [comment]
I have a few other enhancements I made recently. Let me push the new
changes tomorrow before any merging

**Comment by nafisto** [comment]
Thanks @zopf--I'll go ahead and merge changes once made.

Just as a quick heads up, I'm not excited about some of the naming and syntax we've ended up with (e.g. TrueVaultVaultStore, repeating the crud methods, etc.), so I'll probably take a crack at re-working this in a few weeks.  This will be a breaking release so please make sure you reference the 0.2.x line in your npm dependencies.

**Comment by zopf** [comment]
Yeah it's a bit hacky. The especially ugly part is that some TV api methods
accept JSON objects while others only accept form parameters, so there is a
need to use both the JSON client and a string client.

The error message handling should be standardized for the string client too.

What would you suggest for naming conventions?

**Pull request closed without merging**
